### ISSUE TITLE
When checking balance throws JSON error message.

### ISSUE THREAD

**Issue by pyCynical** [pyCynical/smspva#1]
```
Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/py/Desktop/smspva/smspva/__init__.py", line 25, in get_balance
    return self.check_response(r)
  File "/home/py/Desktop/smspva/smspva/__init__.py", line 18, in check_response
    if resp.status_code != 200 or not is_json(resp.json()):
  File "/home/py/Desktop/smspva/smspva/__init__.py", line 6, in is_json
    json_object = json.loads(obj)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
```

**Comment by pyCynical** [comment]
Fixed - 
Was an issue with checking if the response was JSON as seen in the error.
